name: 'analytics'
version: '1.0.0'

profile: 'analytics'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:
  - "target"
  - "dbt_packages"

on-run-start:
  - "CREATE TABLE IF NOT EXISTS {{ target.schema }}.audit_log (
        model_name STRING,
        run_timestamp TIMESTAMP
    )"

models:
  analytics:
    +post-hook:
      - "INSERT INTO {{ target.schema }}.audit_log VALUES ('{{ this }}', CURRENT_TIMESTAMP)"
      
    src:
      +materialized: view
      +schema: SRC
    dim:
      +materialized: table
      +schema: dim

seeds:
  analytics:
    +schema: SRC

data_tests:
  +store_failures: true
  +schema: test_failures