version: 2

models:
  - name: dim_listings_cleansed
    data_tests:
      - minimum_row_count:
          min_row_count: 100
          severity: warn 
    columns:
      - name: listing_id
        data_tests:
          - unique
          - not_null
      - name: host_id
        data_tests:
          - not_null
          - relationships:
              to: ref('dim_hosts_cleansed')
              field: host_id
      - name: room_type
        data_tests:
          - accepted_values:
              values: 
                - 'Entire home/apt'
                - 'Private room'
                - 'Shared room'
                - 'Hotel room'
      - name: minimum_nights
        data_tests:
          - positive_values          

  - name: dim_hosts_cleansed
    description: "Cleansed dimension table containing detailed profiles of Airbnb hosts with normalized attributes." # Model description
    config:
      contract:
        enforced: true 
    columns:
      - name: host_id
        data_type: integer
        description: "The unique primary identifier for each host." #  Column description
        constraints:   
          - type: primary_key
          - type: not_null
        data_tests:    
          - unique
          - not_null

      - name: host_name
        data_type: string
        description: "The verified name of the host profile."
        constraints:   
          - type: not_null
        data_tests:
          - not_null

      - name: is_superhost
        data_type: string
        description: "Flag indicating whether the user has achieved Airbnb Superhost status. 't' for true, 'f' for false."
        data_tests:
          - accepted_values:
              values:
                - 't'
                - 'f'

      - name: created_at
        data_type: timestamp_ntz
        description: "The timestamp when the host profile was originally created."

      - name: updated_at
        data_type: timestamp_ntz
        description: "The timestamp when the host profile records were last updated."